Clean up and export mWater filters download data

In [1]:
import pandas as pd

## Config

In [2]:
# in_file = "/Users/datascience/Desktop/mwater-ashanti,eastern,volta-pipedwater.csv"
in_file = "/Users/datascience/Desktop/mwater-brongahafo-pipedwater.csv"

## Load Data

In [3]:
df = pd.read_csv(in_file)
df.shape

(928, 75)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Data columns (total 75 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Name                                                                926 non-null    object
 1   Description                                                         792 non-null    object
 2   Type                                                                928 non-null    object
 3   GPS Location (latitude)                                             928 non-null    float64
 4   GPS Location (longitude)                                            928 non-null    float64
 5   Administrative region                                               928 non-null    object
 6   Location Accuracy                                                   741 non-null    float64
 7   Location Altitude                                                   361 non-null    float64
 8   Altitude Accuracy                                                   78 non-null     float64
 9   Unique ID                                                           928 non-null    int64
 10  Custom ID                                                           150 non-null    object
 11  Custom ID assigned by                                               102 non-null    object
 12  Photos                                                              744 non-null    object
 13  Primarily agricultural use                                          0 non-null      float64
 14  Primarily livestock use                                             0 non-null      float64
 15  Date of installation                                                233 non-null    object
 16  Drilling method                                                     17 non-null     object
 17  Pump/lifting device                                                 18 non-null     object
 18  Supply for groundwater system                                       5 non-null      object
 19  Supply for piped system                                             250 non-null    object
 20  Treatment works                                                     38 non-null     object
 21  Rehabilitated water point                                           0 non-null      float64
 22  Rehabilitation date                                                 0 non-null      float64
 23  Drilling method (other)                                             0 non-null      float64
 24  Pump lifting device (Other)                                         3 non-null      object
 25  Supply (other)                                                      0 non-null      float64
 26  Treatment Works - Other (please specify)                            1 non-null      object
 27  Provide additional information about supply and treatment systems?  20 non-null     object
 28  Depth (m)                                                           6 non-null      float64
 29  Year of construction or most recent rehabilitation (EFY)            45 non-null     float64
 30  Monitoring                                                          2 non-null      object
 31  Water system                                                        376 non-null    float64
 32  Community                                                           133 non-null    float64
 33  School                                                              28 non-null     float64
 34  Health facility                                                     13 non-null     float64
 35  Household                                                           0 non-null      float64
 36  Project ID                                                          2 non-null      object
 37  TWP Project ID                                                      0 non-null      float64
 38  TWP Project Location                                                0 non-null      float64
 39  Location type                                                       258 non-null    object
 40  Location type - Other                                               9 non-null      object
 41  Piped system type                                                   93 non-null     object
 42  Piped system type (other)                                           85 non-null     object
 43  The Water Trust Uganda Id                                           0 non-null      float64
 44  Country (text)                                                      17 non-null     object
 45  Import code                                                         76 non-null     object
 46  External photo location                                             59 non-null     object
 47  Bar code                                                            0 non-null      float64
 48  Implementing organization                                           266 non-null    object
 49  Installer or driller                                                0 non-null      float64
 50  Funder or donor                                                     2 non-null      object
 51  Rehabilitation implementing organization                            0 non-null      float64
 52  Rehabilitation funder or donor                                      0 non-null      float64
 53  WRA Code                                                            0 non-null      float64
 54  Type (Uganda)                                                       0 non-null      float64
 55  Source ID                                                           0 non-null      float64
 56  Connection type                                                     0 non-null      float64
 57  Meter present                                                       0 non-null      float64
 58  Meter ID                                                            0 non-null      float64
 59  Meter photo                                                         0 non-null      float64
 60  Sector number                                                       0 non-null      float64
 61  admin1                                                              0 non-null      float64
 62  admin2                                                              0 non-null      float64
 63  admin3                                                              0 non-null      float64
 64  admin4                                                              0 non-null      float64
 65  admin5                                                              0 non-null      float64
 66  Water asset                                                         174 non-null    float64
 67  Managed By                                                          928 non-null    object
 68  Added by user                                                       928 non-null    object
 69  Date added                                                          928 non-null    object
 70  Last modified by user                                               508 non-null    object
 71  Date last modified                                                  508 non-null    object
 72  Site Private                                                        927 non-null    object
 73  Previous mWater IDs                                                 36 non-null     object
 74  Pending Approvals                                                   928 non-null    bool
dtypes: bool(1), float64(39), int64(1), object(34)
memory usage: 537.5+ KB

## Clean Data

### Split admin location data

In [6]:
df[["DISTRICT", "REGION", "COUNTRY"]] = df['Administrative region'].str.strip().str.split(",", n=2, expand=True)

In [7]:
df.head(3)

,Name,Description,Type,GPS Location (latitude),GPS Location (longitude),Administrative region,Location Accuracy,Location Altitude,Altitude Accuracy,Unique ID,...,Added by user,Date added,Last modified by user,Date last modified,Site Private,Previous mWater IDs,Pending Approvals,DISTRICT,REGION,COUNTRY
0,Kenyasi No 2 small town water system SP 12,Behind Asutifi Rural Bank,Piped into public tap / standpipe / basin,6.981086,-2.388023,"Asutifi North, Brong Ahafo, Ghana",3.74,NaN,NaN,436276103,...,oopoku_wvgh_enum,2024-03-28T10:32:26.048Z,NaN,NaN,False,NaN,True,Asutifi North,Brong Ahafo,Ghana
1,Kenyasi No 2 small town water system SP 11,Kwaadaso opposite Adum public toilet,Piped into public tap / standpipe / basin,6.979728,-2.389147,"Asutifi North, Brong Ahafo, Ghana",4.80,NaN,NaN,436276110,...,oopoku_wvgh_enum,2024-03-28T10:50:19.556Z,NaN,NaN,False,NaN,True,Asutifi North,Brong Ahafo,Ghana
2,Kenyasi No 2 Adum Florita Newman water supply,Adum opposite Church of Christ,Piped into public tap / standpipe / basin,6.979303,-2.389680,"Asutifi North, Brong Ahafo, Ghana",2.00,NaN,NaN,436276134,...,oopoku_wvgh_enum,2024-03-28T11:05:30.312Z,NaN,NaN,False,NaN,True,Asutifi North,Brong Ahafo,Ghana

### Add Source

In [8]:
df["SOURCE"] = "Public-mWater"

### Clean up columns as needed

In [9]:
df["Description"] = df["Description"].fillna("")
df["Name"] = df["Name"].fillna("")

In [10]:
df.head(3)

,Name,Description,Type,GPS Location (latitude),GPS Location (longitude),Administrative region,Location Accuracy,Location Altitude,Altitude Accuracy,Unique ID,...,Date added,Last modified by user,Date last modified,Site Private,Previous mWater IDs,Pending Approvals,DISTRICT,REGION,COUNTRY,SOURCE
0,Kenyasi No 2 small town water system SP 12,Behind Asutifi Rural Bank,Piped into public tap / standpipe / basin,6.981086,-2.388023,"Asutifi North, Brong Ahafo, Ghana",3.74,NaN,NaN,436276103,...,2024-03-28T10:32:26.048Z,NaN,NaN,False,NaN,True,Asutifi North,Brong Ahafo,Ghana,Public-mWater
1,Kenyasi No 2 small town water system SP 11,Kwaadaso opposite Adum public toilet,Piped into public tap / standpipe / basin,6.979728,-2.389147,"Asutifi North, Brong Ahafo, Ghana",4.80,NaN,NaN,436276110,...,2024-03-28T10:50:19.556Z,NaN,NaN,False,NaN,True,Asutifi North,Brong Ahafo,Ghana,Public-mWater
2,Kenyasi No 2 Adum Florita Newman water supply,Adum opposite Church of Christ,Piped into public tap / standpipe / basin,6.979303,-2.389680,"Asutifi North, Brong Ahafo, Ghana",2.00,NaN,NaN,436276134,...,2024-03-28T11:05:30.312Z,NaN,NaN,False,NaN,True,Asutifi North,Brong Ahafo,Ghana,Public-mWater

### Drop unneeded cols

In [11]:
keep_cols = [
    'Name', 'Description', 'Type',
    'DISTRICT', 'REGION', 'COUNTRY',
    'GPS Location (latitude)', 'GPS Location (longitude)',
    'Location Accuracy', 'Location Altitude', 'Altitude Accuracy',
    'Managed By', 'Location type',
    'Implementing organization', 'Funder or donor', 'Installer or driller',
    'Date of installation', 'Date added', 'Date last modified',
    'Drilling method', 'Pump/lifting device',
    'Supply for groundwater system', 'Supply for piped system', 'Treatment works', 'Depth (m)',
    'Photos',
    'SOURCE',
]

In [12]:
df = df[keep_cols].copy()
df.shape

(928, 27)

In [13]:
df.head(3)

,Name,Description,Type,DISTRICT,REGION,COUNTRY,GPS Location (latitude),GPS Location (longitude),Location Accuracy,Location Altitude,...,Date added,Date last modified,Drilling method,Pump/lifting device,Supply for groundwater system,Supply for piped system,Treatment works,Depth (m),Photos,SOURCE
0,Kenyasi No 2 small town water system SP 12,Behind Asutifi Rural Bank,Piped into public tap / standpipe / basin,Asutifi North,Brong Ahafo,Ghana,6.981086,-2.388023,3.74,NaN,...,2024-03-28T10:32:26.048Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://api.mwater.co/v3/images/e5f30a694fec4d...,Public-mWater
1,Kenyasi No 2 small town water system SP 11,Kwaadaso opposite Adum public toilet,Piped into public tap / standpipe / basin,Asutifi North,Brong Ahafo,Ghana,6.979728,-2.389147,4.80,NaN,...,2024-03-28T10:50:19.556Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://api.mwater.co/v3/images/db6390eb9ec94c...,Public-mWater
2,Kenyasi No 2 Adum Florita Newman water supply,Adum opposite Church of Christ,Piped into public tap / standpipe / basin,Asutifi North,Brong Ahafo,Ghana,6.979303,-2.389680,2.00,NaN,...,2024-03-28T11:05:30.312Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://api.mwater.co/v3/images/515803bb2f3642...,Public-mWater

### Rename Columns

In [14]:
rename_dict = {
    "Name": "Water System",
    "GPS Location (latitude)": "LATITUDE",
    "GPS Location (longitude)": "LONGITUDE",
}

In [15]:
df = df.rename(columns=rename_dict)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Water System                   928 non-null    object
 1   Description                    928 non-null    object
 2   Type                           928 non-null    object
 3   DISTRICT                       928 non-null    object
 4   REGION                         928 non-null    object
 5   COUNTRY                        928 non-null    object
 6   LATITUDE                       928 non-null    float64
 7   LONGITUDE                      928 non-null    float64
 8   Location Accuracy              741 non-null    float64
 9   Location Altitude              361 non-null    float64
 10  Altitude Accuracy              78 non-null     float64
 11  Managed By                     928 non-null    object
 12  Location type                  258 non-null    object
 13  Implementing organization      266 non-null    object
 14  Funder or donor                2 non-null      object
 15  Installer or driller           0 non-null      float64
 16  Date of installation           233 non-null    object
 17  Date added                     928 non-null    object
 18  Date last modified             508 non-null    object
 19  Drilling method                17 non-null     object
 20  Pump/lifting device            18 non-null     object
 21  Supply for groundwater system  5 non-null      object
 22  Supply for piped system        250 non-null    object
 23  Treatment works                38 non-null     object
 24  Depth (m)                      6 non-null      float64
 25  Photos                         744 non-null    object
 26  SOURCE                         928 non-null    object
dtypes: float64(7), object(20)
memory usage: 195.9+ KB

## Export

In [16]:
df.head(3)

,Water System,Description,Type,DISTRICT,REGION,COUNTRY,LATITUDE,LONGITUDE,Location Accuracy,Location Altitude,...,Date added,Date last modified,Drilling method,Pump/lifting device,Supply for groundwater system,Supply for piped system,Treatment works,Depth (m),Photos,SOURCE
0,Kenyasi No 2 small town water system SP 12,Behind Asutifi Rural Bank,Piped into public tap / standpipe / basin,Asutifi North,Brong Ahafo,Ghana,6.981086,-2.388023,3.74,NaN,...,2024-03-28T10:32:26.048Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://api.mwater.co/v3/images/e5f30a694fec4d...,Public-mWater
1,Kenyasi No 2 small town water system SP 11,Kwaadaso opposite Adum public toilet,Piped into public tap / standpipe / basin,Asutifi North,Brong Ahafo,Ghana,6.979728,-2.389147,4.80,NaN,...,2024-03-28T10:50:19.556Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://api.mwater.co/v3/images/db6390eb9ec94c...,Public-mWater
2,Kenyasi No 2 Adum Florita Newman water supply,Adum opposite Church of Christ,Piped into public tap / standpipe / basin,Asutifi North,Brong Ahafo,Ghana,6.979303,-2.389680,2.00,NaN,...,2024-03-28T11:05:30.312Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://api.mwater.co/v3/images/515803bb2f3642...,Public-mWater

In [17]:
df.to_excel("/Users/datascience/Desktop/AFPW-mWater-PipedWaterSystems-BrongAhafo.xlsx", index=False)